adjective = input('Adjective: ')
animal = input('Animal: ')
verb = input('Verb: ')
exclamation = input('Exclamation: ')
verb2 = input('Verb: ')
verb3 = input('Verb: ')
verb4 = input('Verb: ')
emotionAdjective = input('Emotion Adjective: ')
noun = input('Noun: ')

print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb} down the hallway. "{exclamation.capitalize()}"! I yelled. But all I could think to do was to {verb2} over and over. Miraculously, that caused it to stop, but not before it tried to {verb3} right in front of my family. I was so {emotionAdjective} that I decided to {verb4} the {animal}. In the end it was all okay because I tranformed into a {noun}.')