firstName = input('First name: ')
lastName = input('Last name: ')
emailAddress = input('Email Address: ')
phoneNumber = input('Phone Number: ')
jobTitle = input('Job Title: ')
idNumber = input('ID Number: ')
print('ID Card:')
print('----------------------------------------')
print(lastName.upper() + ', ' + firstName.capitalize())
print(jobTitle.title())
print('ID: ' + idNumber)
print()
print(emailAddress.lower())
print(phoneNumber)
print('----------------------------------------')