firstName = input('First name: ')
lastName = input('Last name: ')
emailAddress = input('Email Address: ')
phoneNumber = input('Phone Number: ')
jobTitle = input('Job Title: ')
idNumber = input('ID Number: ')
hairColor = input('Hair Color: ')
eyeColor = input('Eye Color: ')
month = input('Month Started: ')
training = input('Advanced Training Completed (Y/N): ')

print('ID Card:')
print('----------------------------------------')
print(lastName.upper() + ', ' + firstName.capitalize())
print(jobTitle.title())
print('ID: ' + idNumber)
print()
print(emailAddress.lower())
print(phoneNumber)  
print(f'Hair: {hairColor.capitalize():15} Eyes: {eyeColor.capitalize()} ' )
print(f'Month: {month.capitalize():14} Training: {training.capitalize()} ' )
print('----------------------------------------')